-- spec/framing_spec.lua
-- Framing 测试：check_body_len + edge cases + half-packet + sticky packet

local Framing = require("yar.protocol.framing")
local Header = require("yar.protocol.header")
local Packager = require("yar.packager.packager")
local Request = require("yar.message.request")
local Protocol = require("yar.protocol.protocol")
local Util = require("yar.util")
local helpers = require("spec.helpers")

describe("framing", function()
    local p

    before_each(function()
        p = Packager.get(Packager.JSON)
    end)

    describe("check_body_len", function()
        it("should pass normal message", function()
            local req = Request.new({ method = "add", params = { 1, 2 }, provider = "p", token = "t" })
            local msg = Protocol.render(req, p)
            local ok, err = Framing.check_body_len(msg, 10 * 1024 * 1024)
            assert.is_true(ok)
            assert.is_nil(err)
        end)

        it("should reject oversized body", function()
            local req = Request.new({ method = "add", params = { 1, 2 }, provider = "p", token = "t" })
            local msg = Protocol.render(req, p)
            local ok, err = Framing.check_body_len(msg, 1)
            assert.is_nil(ok)
            assert.truthy(string.find(err, "body too large"))
        end)

        it("should pass with default max_body_len", function()
            local req = Request.new({ method = "add", params = { 1, 2 }, provider = "p", token = "t" })
            local msg = Protocol.render(req, p)
            local ok = Framing.check_body_len(msg)
            assert.is_true(ok)
        end)

        it("should pass short data (< HEADER_TOTAL)", function()
            local ok = Framing.check_body_len("short", 1)
            assert.is_true(ok)
        end)
    end)

    describe("edge cases", function()
        it("should receive zero-body message", function()
            local header = Header.new({ id = 999, provider = "p", token = "t", body_len = 0 })
            local zero_body_msg = Util.pad_field(p.name, 8) .. header:pack()
            local sock = helpers.mock_framing_socket(zero_body_msg)
            local data, err = Framing.receive_message(sock)
            assert.is_not_nil(data)
            assert.is_nil(err)
            assert.are.equal(Framing.HEADER_TOTAL, #data)
        end)

        it("should pass zero-body with max=0", function()
            local header = Header.new({ id = 999, provider = "p", token = "t", body_len = 0 })
            local zero_body_msg = Util.pad_field(p.name, 8) .. header:pack()
            local sock = helpers.mock_framing_socket(zero_body_msg)
            local data = Framing.receive_message(sock, 0)
            assert.is_not_nil(data)
        end)

        it("should reject positive body with max=0", function()
            local req = Request.new({ method = "add", params = {}, provider = "p", token = "t" })
            local msg = Protocol.render(req, p)
            local sock = helpers.mock_framing_socket(msg)
            local data, err = Framing.receive_message(sock, 0)
            assert.is_nil(data)
            assert.truthy(string.find(err, "body too large"))
        end)

        it("should receive_exact bytes", function()
            local sock = helpers.mock_framing_socket("ABCDE")
            local exact = Framing.receive_exact(sock, 5)
            assert.are.equal("ABCDE", exact)
        end)

        it("should return nil for receive_exact with insufficient data", function()
            local sock = helpers.mock_framing_socket("AB")
            local short, serr = Framing.receive_exact(sock, 5)
            assert.is_nil(short)
            assert.is_not_nil(serr)
        end)
    end)

    describe("half-packet attack", function()
        it("should reject data < HEADER_TOTAL", function()
            local sock = helpers.mock_framing_socket(string.rep("X", 10))
            local data, err = Framing.receive_message(sock)
            assert.is_nil(data)
            assert.is_not_nil(err)
            assert.truthy(string.find(err, "short header") or string.find(err, "closed") or string.find(err, "short"))
        end)

        it("should reject empty socket", function()
            local sock = helpers.mock_framing_socket("")
            local data, err = Framing.receive_message(sock)
            assert.is_nil(data)
            assert.is_not_nil(err)
        end)

        it("should reject partial header", function()
            local sock = helpers.mock_framing_socket("JSON\0\0\0\0" .. string.rep("\0", 40))
            local data, err = Framing.receive_message(sock)
            assert.is_nil(data)
            assert.is_not_nil(err)
        end)

        it("should reject short body (body_len > available)", function()
            local fake_header = Header.new({ id = 1, provider = "p", token = "t", body_len = 200 })
            local short_body_msg = Util.pad_field("JSON", 8) .. fake_header:pack() .. string.rep("X", 50)
            local sock = helpers.mock_framing_socket(short_body_msg)
            local data, err = Framing.receive_message(sock)
            assert.is_nil(data)
            assert.is_not_nil(err)
        end)
    end)

    describe("sticky packet framing", function()
        it("should split two concatenated messages", function()
            local req1 = Request.new({ method = "add", params = { 10, 20 }, provider = "p1", token = "t1" })
            local msg1 = Protocol.render(req1, p)
            local req2 = Request.new({ method = "add", params = { 30, 40 }, provider = "p2", token = "t2" })
            local msg2 = Protocol.render(req2, p)
            local combined = msg1 .. msg2

            local sock = helpers.mock_framing_socket(combined)
            local data1 = Framing.receive_message(sock)
            assert.is_not_nil(data1)
            assert.are.equal(#msg1, #data1)
            local payload1, header1 = Protocol.parse(data1, p)
            assert.are.equal(10, payload1.p[1])
            assert.are.equal(req1.id, header1.id)

            local data2 = Framing.receive_message(sock)
            assert.is_not_nil(data2)
            assert.are.equal(#msg2, #data2)
            local payload2, header2 = Protocol.parse(data2, p)
            assert.are.equal(30, payload2.p[1])
            assert.are.equal(req2.id, header2.id)

            local data3, err3 = Framing.receive_message(sock)
            assert.is_nil(data3)
            assert.is_not_nil(err3)
        end)

        it("should split three concatenated messages", function()
            local req1 = Request.new({ method = "add", params = { 10, 20 }, provider = "p1", token = "t1" })
            local msg1 = Protocol.render(req1, p)
            local req2 = Request.new({ method = "add", params = { 30, 40 }, provider = "p2", token = "t2" })
            local msg2 = Protocol.render(req2, p)
            local req3 = Request.new({ method = "add", params = { 50, 60 }, provider = "p3", token = "t3" })
            local msg3 = Protocol.render(req3, p)
            local triple = msg1 .. msg2 .. msg3

            local sock = helpers.mock_framing_socket(triple)
            local expected = { req1, req2, req3 }
            for _, expected_req in ipairs(expected) do
                local d = Framing.receive_message(sock)
                assert.is_not_nil(d)
                local _, hd = Protocol.parse(d, p)
                assert.are.equal(expected_req.id, hd.id)
            end
            local data_end = Framing.receive_message(sock)
            assert.is_nil(data_end)
        end)
    end)
end)
